spring.application.name=vaultiq
spring.docker.compose.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/vaultiq
spring.datasource.username=vaultiq_user
spring.datasource.password=vaultiq123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
gemini.api.key=${GEMINI_API_KEY}
groq.api.key=${GROQ_API_KEY}